// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABc7QOmCL05xsfB179MosbVusArTbPCiw',
    appId: '1:44398785703:web:84e0706dd6157963985782',
    messagingSenderId: '44398785703',
    projectId: 'programa-menthor',
    authDomain: 'programa-menthor.firebaseapp.com',
    storageBucket: 'programa-menthor.appspot.com',
    measurementId: 'G-ZWJ3528TP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr5j7EJLNVNBggmsuqdtVH1mIUPw0cxBQ',
    appId: '1:44398785703:android:6faec785883b3532985782',
    messagingSenderId: '44398785703',
    projectId: 'programa-menthor',
    storageBucket: 'programa-menthor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_FWQORd6NLZLUXjuvamtoLSGXz3ROCUI',
    appId: '1:44398785703:ios:37329054536ca1e4985782',
    messagingSenderId: '44398785703',
    projectId: 'programa-menthor',
    storageBucket: 'programa-menthor.appspot.com',
    iosClientId: '44398785703-v76f8u7g7alujjlra1khpk2r8f3b1v22.apps.googleusercontent.com',
    iosBundleId: 'com.example.esiTfgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_FWQORd6NLZLUXjuvamtoLSGXz3ROCUI',
    appId: '1:44398785703:ios:37329054536ca1e4985782',
    messagingSenderId: '44398785703',
    projectId: 'programa-menthor',
    storageBucket: 'programa-menthor.appspot.com',
    iosClientId: '44398785703-v76f8u7g7alujjlra1khpk2r8f3b1v22.apps.googleusercontent.com',
    iosBundleId: 'com.example.esiTfgApp',
  );
}
